### ISSUE TITLE
Container doesn't contain

### ISSUE THREAD

**Issue by amon84** [containers-everywhere/contain-google#1]
expected to be logged out and see the container bar below the tab and the indicator in the URL/search bar.

tried visiting an internal link on a google site, reload, ctrl-reload, restart of browser. nothing changed

no indicators visible, no other indication taht the container is working properly.
(other addons, facebook and twitter container work)

**Comment by Perflyst** [comment]
Sorry for this mistake.
Fixed in release [1.0.1](ad52c1afd5c980b415ec17b8370d8f8963b74b62). Please update the addon.
