### ISSUE TITLE
feedproxy.google.com creates multiple tabs

### ISSUE THREAD

**Issue by Generator** [containers-everywhere/contain-google#10]
Opening links from ``feedproxy.google.com`` creates multiple tabs (3 or 4 tabs) of the same link.  
Example: http://feedproxy.google.com/~r/Phoronix/~3/HM6Scx2dllQ/scan.php  
Links should reopen on the same tab

**Comment by Perflyst** [comment]
Works here quite normally, such a problem does not occur.
Which addons do you still have installed? You can find your installed versions on `about:support`

**Comment by Generator** [comment]
Tried with all other addons disabled, and there's no issue, tried enabling one by one and test it, there's no issue till i restart the browser.  Also tried with a test clean profile no issue also copied prefs.js to test profile, and no issue.  

**about:support log:**
[firefox_support.log](https://github.com/containers-everywhere/contain-google/files/1933451/firefox_support.log)

**Issue demo:**
https://imgur.com/a/FASv4st

**Comment by Perflyst** [comment]
Thank you for the information. You have tons of addons to analyze all will take a time...

You could delete Google Container and create a manual rule about Temporary Containers if the same problem occurs there. If necessary, also test directly via Multi Account Containers.

**Comment by Perflyst** [comment]
Would be very nice. I installed all the addons but I have not such an issue.
Maybe it is a special setting in an addon.

**Comment by Generator** [comment]
Problem no longer persists, closing the issue till more information.

**Comment by enigmatic-system** [comment]
I am having this issue currently.
