### ISSUE TITLE
Disable "Google Container" putting addons.mozilla.org in a Google Container

### ISSUE THREAD

**Issue by aquila-XP** [containers-everywhere/contain-google#102]
When I open a link related to Firefox extensions from a Google search page, I noticed that it is in a Google Container.
Please fix this "feature" that puts URL - `https://addons.mozilla.org/en-US/firefox/` in a Google Container.

**Comment by hackerncoder** [comment]
This is indeed a "feature" (read bug).

I have done further testing using Multi-Account Container and it too can't auto open addons.mozilla.org in a container, so it seems like addons.mozilla.org has some sort of blocker on addons.

**Comment by hackerncoder** [comment]
I believe there is nothing we can do, addons.mozilla.org is immune to what I expect are all addons to protect you from a bad addon, and therefore I will be closing the issue.
