### ISSUE TITLE
Google is no longer contained inside the container

### ISSUE THREAD

**Issue by markotaht** [containers-everywhere/contain-google#110]
I just noticed that the google container has stopped functioning. I had YT tab open, on the tab bar it had line under the name signalling that is in the container. I closed YT and opened it again, the bar was gone. Same goes with Gmail  and all the other google features. I have not installed any new add on to frefox. It just stopped working.

**Comment by Perflyst** [comment]
Can you check if you are running the latest version 1.5.3? There was a bug introduced in 1.5.2 which got fixed today

**Comment by markotaht** [comment]
Seems to be 1.5.2

**Comment by Perflyst** [comment]
I guess it somehow got updated to 1.5.2 even if I disabled this version on AMO. Thanks for reporting that it works again.
