### ISSUE TITLE
Does not work with third party SSO

### ISSUE THREAD

**Issue by SarenCurrie** [containers-everywhere/contain-google#111]
My company uses a third party SSO to login to Google, since the auth for this doesn't open in the container, I am unable to login to my work Google account.

**Comment by situplastik** [comment]
same problema here: #113

**Comment by thorgrin** [comment]
I use the following workaround:
- turn on google container
- open the google login page
- disable the google container addon
- enter mail for the 3rd party SSO, finish sign on
- turn on google container again

This way, I'm signed in the third party account and can use it in the google container. Not sure how much information it leaks though.

**Comment by situplastik** [comment]
As you are google-logged outside google-container plugin, I guess google can track in all world wide web . The solution that I propose is a list of domains where you can accept to interact with google (adding them into google-container).

I expect in some days resolve the PR & add them into next release of the plugin :)

**Comment by Perflyst** [comment]
Thanks to https://github.com/containers-everywhere/contain-google/pull/114, with version 1.5.4 you can add custom additional urls / domains to google container
