### ISSUE TITLE
Site/domain feature in preferences

### ISSUE THREAD

**Issue by situplastik** [containers-everywhere/contain-google#113]
Even if you don't want to tracked by google, sometimes need to use your google account (by oAuth) to log in in some website. I'm developing a website for a client that want to admit that option. Basically, configure the addons in order to admit connections from `service.mywebsite.com`

Looking on preferences, there is a whitelist textarea but is for google sites.

![Captura de Pantalla 2021-01-11 a les 12 22 23](https://user-images.githubusercontent.com/19546264/104176751-0973fd00-5408-11eb-958c-899e1546a18e.png)

It would be great if there will be another textarea in order to put domain/subdomain allowed to be openned with Google Container. Or at least accept comunication by POST or GET.

Thanks for the addons, it works perfecty ;)

**Comment by hackerncoder** [comment]
Maybe we need to #112 and get a similar toolbar icon with features, such as the one requested here, and in #90.

**Comment by situplastik** [comment]
@hackerncoder it would be interesting to update the plugin, for sure. I haven't got plenty of time to do it; anyone have it? As alternative, I've just made a PR in order to solve the problem until the core update arrive :)

Hope @Perflyst like it.

**Comment by hackerncoder** [comment]
I just have to find time to update it. This way of doing it is bad, from a usability standpoint. But also from a code standpoint, we are just piling on code. Yours is great, you redid some code to use it for both, but not everything can or does get reused in the same way.

**Comment by situplastik** [comment]
@hackerncoder totally agree with your comment, my contribution is not as reused as could be, but it solve a particular problem. I didn't know that a core update was planned in short/medium time, I saw that you ask for and no-one hands up...

Maybe, a well working route would be release a version with that feature in order to close many issues. When the core update will be done, we can waste or change the code I created  :) (as you said that the feature is already)
