### ISSUE TITLE
Will this become an arms race? 

### ISSUE THREAD

**Issue by just1689** [containers-everywhere/contain-google#12]
I'm just curious. Perhaps there's something I've misunderstood. It is my understanding that Google uses exactly the insights that this plug in blocks for effective ad targeting and profiling. If that is correct, this work (which is great BTW) could have a direct effect the quality of Googles view of the people out there on the web. Would Google not actively search for a way around this?

**Comment by Perflyst** [comment]
Thanks for your interest. Google continues to track you. But they can't do it as well on non-google pages, for example. When you search for something on google and click on a search result, google knows exactly when you want to go where. There is a addon to prevent this. It is called [Do not track me Google](https://addons.mozilla.org/en-US/firefox/addon/dont-track-me-google1/).

Also, if you have a mobile phone with Google apps/services installed, your location, search behavior, app usage and so on will be tracked.

To the point that google wants to find a way around it. Why would they? The few users have no meaning for google. Who really wants to get away from Google that can do that. Other search engine, google free ROM for mobile.
