### ISSUE TITLE
Because of the orange bar on the tab, I mistake it for the active tab.

### ISSUE THREAD

**Issue by hboetes** [containers-everywhere/contain-google#126]
This happens to me constantly, because of the orange bar on the tab, I mistake it for the active tab.
![image](https://user-images.githubusercontent.com/2285225/135330145-ce5ab049-6a6a-4479-9004-9c592ef819c9.png)

I really like this container app, but I would like to request one change, or the option to make it optional: To disable the orange bar at the top, since I can't see which tab is active.

Thanks for your great add-on and your consideration.

**Comment by gitdev-bash** [comment]
You can change the color of the container with the Multi-Account Containers add-on by Mozilla.

**Comment by hboetes** [comment]
OK, thanks for the heads-up.
