### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by DanitiKain** [containers-everywhere/contain-google#13]
I am sure it may be a conflict with one of my other container add-ons.  However I would like to have Google and Facebook containers as well as temporary containers all work together as one unit.  Facebook Containers works with this setup just fine.  However Google Containers does not.  It maybe a collaboration effort with the temporary containers developer to get this working.

Cookie AutoDelete	2.1.2	true	CookieAutoDelete@kennydo.com
Decentraleyes	2.0.3	true	jid1-BoFifL9Vbdl2zQ@jetpack
Facebook Container	1.3.1	true	@contain-facebook
Google Container	1.0.2	true	@contain-google
HTTPS Everywhere	2018.4.11	true	https-everywhere@eff.org
Privacy Badger	2018.4.23	true	jid1-MnnxcxisBPnSXQ@jetpack
Switch Container Plus	0.14	true	{d5ac33ed-723c-402b-b17c-e7bbb0d3a80d}
Temporary Containers	0.89	true	{c607c8df-14a7-4f28-894f-29e8722976af}
uBlock Origin	1.16.0	true	uBlock0@raymondhill.net
xclear	1.8.1-signed	false	xclear@as-computer.de

**Comment by Perflyst** [comment]
You cannot use Facebook and Google Container at the same time.

**Comment by Perflyst** [comment]
I have the same addons. I installed Google Container and Facebook Container. Works perfect.

Do you have some `Always open in` or other website rules from google or facebook in thetemporary containers addon? Do you use the automatic mode?

**Comment by DanitiKain** [comment]
Sorry it is working it was just the same color as my temp containers(red) so I assumed it was not working.  Only thing that stinks is 3 windows open when I go to google.com.  I like temp containers feature of opening new windows on every new tab.  I think it is conflicting though with both the FB and Google containers tab cause doing to either with this feature on opens multiple tabs which stinks a little.  Any ideas on how to resolve this without turning off that ever new container its a temp tab.  I often forget when clicking a link or opening a new window to use temp tabs.

**Comment by Perflyst** [comment]
This problem is already reported to the temporary containers developer. Good to know it works know, I will close this issue.
