### ISSUE TITLE
Respect the `openerTabId` of the original tab

### ISSUE THREAD

**Issue by piroor** [containers-everywhere/contain-google#137]
The tab reopened by the Google Container doesn't respect the `openerTabId` of the original tab. It is used by some addons to detect relations of tabs (including my [Tree Style Tab](https://addons.mozilla.org/firefox/addon/tree-style-tab/)) and losing it causes compatibility problems with such addons, for example [TST case](https://github.com/piroor/treestyletab/issues/3147).

I think you just need to add `openerTabId: tab.openerTabId,` for parameters of [`tabs.create()`](https://github.com/containers-everywhere/contain-google/blob/7675291ce19cf1f7eb96f6361f81839719db245f/background.js#L259). Could you consider about that?

**Comment by hackerncoder** [comment]
Added in #134
