### ISSUE TITLE
Open search results in new container tab instead of the same tab

### ISSUE THREAD

**Issue by ideal2545** [containers-everywhere/contain-google#16]
can there be an adjustment so it does not open in the same tab when you click a link?

**Comment by Perflyst** [comment]
You can easily middle mouse click them to open a new tab.

**Comment by ideal2545** [comment]
That makes sense but are you able to adjust the default behavior for search so that you don't have to middle-mouse click?

**Comment by Perflyst** [comment]
I'm sure that's possible. However, I have almost nothing to do with Javascript. I reopen this issue and tag it with help wanted. Maybe @stoically can help here.

**Comment by doronbehar** [comment]
I'm experiencing this behaviour as problematic as well but my opinion is that this is out of the scope of this add-on. Another add-on should be created that will do just that or you can workaround this using a greesemonkey script like this: https://greasyfork.org/en/scripts/12367-open-links-in-new-tab

**Comment by Perflyst** [comment]
Thank you for the script. I will add it in the README.md later. If you are faster I will also merge a PR. ;)

**Comment by deadscreem** [comment]
The main issue with this is that the default of opening in the same tab pops the site out of the google tab, and the google tab then disappears so you can't switch back to the search results by switching tabs or using the history back button.

The grease monkey script is a neat idea, except it doesn't seem to work in latest firefox 64.0. Does anybody have a solution that works with ff64+ ??

**Comment by siffegh** [comment]
In the lower R. corner of the Google page, click 'Settings'. In the 'Where results open' section, click 'Open each selected result in a new browser window'. 

Then in your browser, go to Menu > Options > General > Tabs and check 'Open links in tabs instead of new windows'.

**Comment by deadscreem** [comment]
OH! That works perfect! Thanks!!

**Comment by Karunamon** [comment]
I gotta say, this is kind of a pain in the ass and breaks my workflow. The whole "opening in new tabs" thing tends to cause one to create a bunch of extra tabs unless they're fastidious about closing them, and before long, I've got 100+ tabs open and Firefox has slowed to a crawl.

I'd really rather not re-learn years of muscle memory.

From the standpoint of the addon, would it be possible to push a back button entry of the previous google search page visited when clicking something on the SERP?

**Comment by harrv** [comment]
> The main issue with this is that the default of opening in the same tab pops the site out of the google tab, and the google tab then disappears so you can't switch back to the search results by switching tabs or using the history back button.

Exactly! This is driving me nuts. Click on one Google result and there is no way to get back to your list of Google results.

> In the lower R. corner of the Google page, click 'Settings'. In the 'Where results open' section, click 'Open each selected result in a new browser window'.
> 
> Then in your browser, go to Menu > Options > General > Tabs and check 'Open links in tabs instead of new windows'.

Many of us who are interested in privacy don't save Google cookies beyond the current session either. I would suspect this particular solution won't work in subsequent browser sessions if you don't save Google cookies.

> From the standpoint of the addon, would it be possible to push a back button entry of the previous google search page visited when clicking something on the SERP?

I hope this is possible.

**Comment by Perflyst** [comment]
Should be fixed via #62
