### ISSUE TITLE
googleusercontent.com not in google container

### ISSUE THREAD

**Issue by smiddy** [containers-everywhere/contain-google#24]
For the proper use of Google drive it would be good to have the domain googleusercontent.com in the google containers as well.

**Comment by Perflyst** [comment]
Was already fixed, I created a new release. Check for an update.

Thanks!

**Comment by smiddy** [comment]
No it works correct. Thanks! Are you on liberapay or similar?

**Comment by Perflyst** [comment]
I hope you mean "now" and not "no".

Liberapay? No, since this is just a fork and the real work of mozilla I do not accept donations.
You're doing me a favor by giving the repo a star.

**Comment by smiddy** [comment]
I mean "now". Thanks anyway!
