### ISSUE TITLE
Clicking a google search link removes the search tab

### ISSUE THREAD

**Issue by Ross65536** [containers-everywhere/contain-google#31]
I'm using firefox on Ubuntu (but also the same on Windows) and when I click a link from a google search the google tab is closed, 'replaced' by the link but the google search isn't in the new tab's history. This is really frustrating since I frequently have to check my browser's history to get back the search.

It would be better to either add the google search to the new tab's history or to not close the search tab when a link is clicked.

**Comment by Perflyst** [comment]
This is out of scope for this addon. You could click the search result middle mouse or make further finer settings with Temporary Containers.

See #4
