### ISSUE TITLE
Issue with SAML Idp

### ISSUE THREAD

**Issue by EliteWarrior** [containers-everywhere/contain-google#37]
In case google redirects to 3rd party URL for logging in, context goes out of container and once logged in on Idp and context returns to google and thus container. It remains stuck with blank page. I believe this is because the authorization data is lost in switching the containers. 
Will it be possible to fix this scenario, or will it be WONT FIX ?

I haven't tried with OAUTH/OIDC etc but think same issue would occur.

**Comment by Perflyst** [comment]
The authorization data is stored in a cookie, containers seperate cookies. The "issue" is already described in the readme: https://github.com/containers-everywhere/contain-google#logging-in-or-creating-accounts-on-other-websites-using-google

This is not a real issue more a feature / use case of containers.
