### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by siffegh** [containers-everywhere/contain-google#38]
The Google Apps, Notifications, and Google Account icons (upper R. corner) do not appear, so there's no way to sign out.

**Comment by Perflyst** [comment]
This seems not to be releated to the addon. Please open your browser console (press F12), click network and reload with F5. There should be some 404 or other error codes.

**Comment by siffegh** [comment]
Disabled everything I could think of but forgot about my Stylish theme - where I had hidden that panel.
