### ISSUE TITLE
Search results window closed on opening new window

### ISSUE THREAD

**Issue by frost-au** [containers-everywhere/contain-google#4]
Hi
Every time I open a search result in a new window the search results window is closed which is rather irritating.

**Comment by Perflyst** [comment]
Thanks for the report. This is a fork from the [Facebook Container](https://github.com/mozilla/contain-facebook/issues). Please report this issue there, but check if it is already known.

**Comment by Perflyst** [comment]
You could click the search result middle mouse or make further finer settings with [Temporary Containers](https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/).

**Comment by frost-au** [comment]
Nice. That saves me from having to uninstall the plugin. It was getting unusable otherwise.

**Comment by Perflyst** [comment]
If you have any other questions or problems, please open a new issue. Thanks!
