### ISSUE TITLE
Not able to log in with google account on non-google services

### ISSUE THREAD

**Issue by michaldybczak** [containers-everywhere/contain-google#42]
I found a problem when trying to log in to services with google account. For example, imgur. I tried to add it to google container but unlike usual containers, it doesn't allow for it. I open google tab, open imgur in it and it switches the container to general, which is annoying because google log in window seem not to able to connect to the main site (imgur) and hangs indefinitely.

Is there a solution for that with that extension being on?

**Comment by Perflyst** [comment]
There is a solution: https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/

It is not possible and also dumb to include every domain/websites which have the option to login with google. Please create your own Container with your custom needs.

**Comment by michaldybczak** [comment]
That's not ideal. The perk of using your plugin is that it already opens all google services in proper container and there is a lot of them. I don't have to worry or do manual actions and I love it, but for the case I described, this isn't working.
Also, I don't want to put together non-google and google sites just because it uses google to log in.

This is also a problem with the multi-account containers. For example, I have a bank site on bank container but some shopping sites re-direct to the bank site to finalize the purchase. In that case, it's not possible, so I guess I would have to put the bank together with a shopping container.

The worst thing is, I cannot predict all scenarios and usually came across an issue that is made by containers and then I have to change everything.

This is frustrating and not very user-friendly so I hoped there is some solution to deal with such, pretty common, issues.

For example, a site belongs to one container but has an allowance to be opened in another container if needed (of course with a different set of cookies, proper to the other container). I thought that such solution should already be used. After all, container plugins aren't a novelty anymore.

**Comment by Perflyst** [comment]
Your example is not possible with the container API as far as I know.

**Comment by michaldybczak** [comment]
So you are saying I should bring the idea to the original multi-container plugin and once they implement it in their API, your plugin will port that feature as well?

**Comment by chaoscreater** [comment]
Maybe some sort of site exclusion implementation or temporarily disable the addon (like you can do with UBlock Origin) will at least help a bit?

**Comment by michaldybczak** [comment]
Yeah, an easy disabling add-on could help. It would have to be an option after clicking the addon icon. We can disable addon from addon pages but that's cumbersome on a daily basis and it would be better not to disable addon completely but only shut it down while still addon being active, like uBlock does.
