### ISSUE TITLE
opening a non-google link from a google container opens the link in a google container

### ISSUE THREAD

**Issue by MaliusArth** [containers-everywhere/contain-google#57]
clicking on a non-google link from within a google container opens the link in a google container.

expected: open the link in no container or in a different container (depending on other container addons)

**Comment by kendallcorner** [comment]
Actually, for me it opens in the same tab, but that tab becomes non-google, which deletes the google tab I was working in. I think for google.com results only it should open links in a new non google window by default. I can try to look at it if @Perflyst is accepting PRs.

**Comment by Perflyst** [comment]
Of course I accept PRs, feel free to code!

**Comment by kendallcorner** [comment]
Current behavior: search results tab are removed and the back button does not function.
![Peek 2019-08-09 09-15](https://user-images.githubusercontent.com/3195251/62785857-12300900-ba87-11e9-8ea3-1d35831e54e7.gif)

**Comment by kendallcorner** [comment]
I've added a commit that does this instead. Let me test it for a few days and then I'll send a PR.
![Peek 2019-08-09 09-17](https://user-images.githubusercontent.com/3195251/62786237-cdf13880-ba87-11e9-805f-b2a1dd239d9e.gif)

**Comment by kendallcorner** [comment]
Original fix has some side effects with tracker links, so my second commit treats it slightly differently and only works for search pages.

**Comment by Perflyst** [comment]
Fixed via #62
