### ISSUE TITLE
Option to disable on developers.google.com

### ISSUE THREAD

**Issue by Kilbourne** [containers-everywhere/contain-google#59]
Hi, 
thanks for the add-on. Is possible to have this feature ( or maybe a textarea where insert whitelisted URLs?)

**Comment by robertl87** [comment]
Same for YouTube, Search and Maps: It'd be nice to have them excluded to do anonymous searches where you don't need an account.

**Comment by situplastik** [comment]
Nowadays the addon have a whitelisted URLs. That issue should be cloused @Perflyst
