### ISSUE TITLE
9to5google.com tries to open in the google container but couldn't and then tries again...

### ISSUE THREAD

**Issue by ppusher** [containers-everywhere/contain-google#63]
I use 'Google Container' along with 'Firefox Multi-Account Containers' and 'Temporary Containers addons.

When I try to open 9to5google.com it keeps trying to open in Google container but gets kicked out to open in non-Google  container but gets pulled in again to open in Google container and the  loops keeps repeating itself.

Is this because of the addon combination I use or is it just a bug?

**Comment by ppusher** [comment]
Same thing happening with phandroid,com the 'android' in the domain is likely triggering it. 

Please exclude phandroid.com and 9to5google.com.

Thank you

**Comment by Perflyst** [comment]
closed with https://github.com/containers-everywhere/contain-google/pull/89
