### ISSUE TITLE
Exclude imglike.com

### ISSUE THREAD

**Issue by ppusher** [containers-everywhere/contain-google#68]
I use 'Google Container' along with 'Firefox Multi-Account Containers' and 'Temporary Containers addons.

When I try to open imglike.com it tries to open in the Google container but can't and the tab is stuck in a loop and never opens. Not sure why it wants to open in the Google Container.

**Comment by aventuraviper** [comment]
imglike opens fine for me (automatically into a google container). Im using Nightly without Temporary Containers (but have multi-account and google container addons). 

Have you got a conflicting rule in any of those?

**Comment by ppusher** [comment]
> imglike opens fine for me (automatically into a google container)

 That itself is unusual isn't it? imglike.com should not be opening in the google container in the first place.

**Comment by aventuraviper** [comment]
It appears to be happening because "like.com" is listed as a google service on line  17. Any domain name that ends like.com will be captured in the google container (such as like4like.com).

**Comment by Perflyst** [comment]
closed with https://github.com/containers-everywhere/contain-google/pull/89
