### ISSUE TITLE
Ability to exclude Youtube or have Youtube as its own container

### ISSUE THREAD

**Issue by aventuraviper** [containers-everywhere/contain-google#69]
Due to upcoming Youtube TOS changes (See [here](https://mashable.com/article/youtube-new-terms-of-service-no-longer-commercially-viable/?europe=true) and [here](https://www.youtube.com/t/terms?preview=20191210#main)), I was wondering if the add-on could be updated to have options for how to handle youtube.com?

Essentially, I'm thinking that currently it isn't possible to use youtube in a logged-out state if logged in to google in firefox already. Treating youtube as a seperate container (or removing it from the addon) would allow for being logged in to google account but not to youtube and avoid issues with the new TOS.

**Comment by Perflyst** [comment]
There is https://invidio.us - https://github.com/omarroth/invidious
If you are worried about YouTube use this, anyway I will keep this open.

**Comment by aventuraviper** [comment]
My apoligies, I had not seen the options tab beneath the description in firefox addons manager.
