### ISSUE TITLE
[Q] Is there any way to add config or something to use this addon with any domain?

### ISSUE THREAD

**Issue by dehghani-mehdi** [containers-everywhere/contain-google#71]
Hi,

Is it possible?
Have you any plan about it? if not and if it's possible, would you help to understand which parts should be changed in order to achieve similar behavior?

One addon per domain is also ok, e.g Reddit Container, Apple Container, ...

**Comment by ShaunaGordon** [comment]
I think for that, you'll want [Firefox's Multi-Account Containers](https://github.com/mozilla/multi-account-containers), which provides more (and more general) container control.

**Comment by dehghani-mehdi** [comment]
That's correct, I don't use `contain-google` addon anymore, because of that and also the face that this issue doesn't get any feedback from the owner, I close this issue.
