### ISSUE TITLE
The domain nomoregoogle.com is opened in the Google container but it shouldn't

### ISSUE THREAD

**Issue by mastazi** [containers-everywhere/contain-google#74]
As far as I know the domain nomoregoogle.com is not affiliated with Google in any way (in fact, it helps people finding alternatives to Google services). 

The footer in the homepage says "This site is non-commercial and not affiliated with Google or any of the alternatives listed here." 

But when I visit the website, it's opened in the Google container. I think this behaviour should be rectified.

**Comment by Perflyst** [comment]
Closed with #89
