### ISSUE TITLE
Can not authenticate .edu account

### ISSUE THREAD

**Issue by jacobhillock** [containers-everywhere/contain-google#76]
When contain-google is activated, I log into the account, and then the browser stops trying to authenticate my .edu account. I am unable to replicate the issue rn but it got stuck at a url like:

https://www.google.com/a/SCHOOL.edu/

**Comment by jacobwhall** [comment]
I had the same problem and [forked the repo](https://github.com/jacobwhall/contain-google-with-wm) to add my institution's authentication server to the container. Maybe we could add a feature to this extension that allows people to do that in a GUI.

**Comment by hackerncoder** [comment]
See PR #114.

**Comment by Perflyst** [comment]
Thanks to https://github.com/containers-everywhere/contain-google/pull/114, with version 1.5.4 you can add custom additional urls / domains to google container
