### ISSUE TITLE
Allow login to google in another container used for specific google service

### ISSUE THREAD

**Issue by julianstirling** [containers-everywhere/contain-google#78]
I use `contain-google` to use google without being logged it. I have a separate container for Google Scholar where I want to be logged in to manage my profile. `contain-google` logs me out in my Scholar container when enabled, it also stops me logging in on my scholar container.

**Comment by davidjade** [comment]
This is a major issue if you need to use containers to use separate google accounts. As it is now, I open my custom container, go to a google site and it spawns a never ending loop of re-opening the tab in google container, then my container, then google container, etc.. creating more and more tabs with each loop. It never stops.
