### ISSUE TITLE
firebaseapp.com not contained

### ISSUE THREAD

**Issue by rolandog** [containers-everywhere/contain-google#79]
While visiting `learndigital.withgoogle.com/digitalworkshop`, and---when logging in---I was redirected through `*.firebaseapp.com`, which wasn't contained.

Could this domain---and subdomains---be added to the repository? When visiting `firebaseapp.com`, you end up redirected to `firebase.google.com`, btw.

**Comment by situplastik** [comment]
I've just check and now it works (firebase.google.com).

Nevertheless, problems like these would be solved if we have some textarea on preferences in order to put domain where we want to use Google Container as well #113

**Comment by Perflyst** [comment]
Thanks to https://github.com/containers-everywhere/contain-google/pull/114, with version 1.5.4 you can add custom additional urls / domains to google container
