### ISSUE TITLE
add option to ignore /preferences

### ISSUE THREAD

**Issue by dawnarius** [containers-everywhere/contain-google#82]
Please add option to ignore /preferences so we can custumize search results when searching
When ignoring /search the search results are presented in google.com default preferences, since I travel a lot sometimes I get results in Finnish, french, german etc. Its pretty annoying

**Comment by breadsanta** [comment]
Maybe /preferences should be ignored when /search is selected?

**Comment by aurelienlux** [comment]
I've created a pull request with the option to ignore /preferences and /setprefs:
https://github.com/containers-everywhere/contain-google/pull/103

**Comment by hackerncoder** [comment]
Ignoring /preferences is now possible. As such this issue is no longer needed, therefore I am closing it. If you think this incorrect please leave a comment explaining why.
