### ISSUE TITLE
Google container doesn't let me login in Castbox

### ISSUE THREAD

**Issue by Git-happiness** [containers-everywhere/contain-google#84]
So, I had trouble login in to Castbox with my Google account. The site opens a new window to redirect to Google accounts login, but it never does, it stays blank. After experimenting with disabling/enabling  all my add ons on Firefox, I figured out it was Google container that caused the problem. It doesn't let Castbox site to redirect to Google. Once I disable the addon, it works fine. Maybe adding a "whitelist" option would be a good idea. Thanks.

**Comment by isaaclw** [comment]
I'm also confused by this because reddit enhancement suite's google drive sync seems to work, and I'm not sure why *that* auth works, but other things like 'tasksboard.app' don't.

**Comment by situplastik** [comment]
same problem here #113

**Comment by Perflyst** [comment]
Thanks to https://github.com/containers-everywhere/contain-google/pull/114, with version 1.5.4 you can add custom additional urls / domains to google container

**Comment by Perflyst** [comment]
Thanks to https://github.com/containers-everywhere/contain-google/pull/114, with version 1.5.4 you can add custom additional urls / domains to google container

**Comment by hackerncoder** [comment]
You uuuhhhh.. Wrote that twice and opened it again.
