### ISSUE TITLE
.google sites not opened in Google container

### ISSUE THREAD

**Issue by critical-bug** [containers-everywhere/contain-google#88]
The extension opens some `.google` sites in normal tab. (Tell me if I had to reopen #45.)

List of non Google-container sites I found:

* https://wellbeing.google/
* https://crisisresponse.google/
* https://grow.google/
* https://covid19.google/ (redirects to https://www.google.com/covid19/)
* https://research.google/
* https://safety.google/
* https://sustainability.google/
* https://chromeenterprise.google/
* https://opensource.google/
* https://health.google/
* https://dns.google/
* https://teachfromanywhere.google/
* https://diversity.google/
* https://elections.google/
* https://protectingchildren.google/
* https://teachfromanywhere.google/
* http://teachfromhome.google/ (redirects to https://teachfromanywhere.google/ )

I've checked up to 100th search results today (2020-07-22) for both
https://www.bing.com/search?q=site%3agoogle&pc=MOZI and
https://www.google.com/search?q=site:.google&client=firefox-b-e with Google Container 1.5.0 .

**Comment by hackerncoder** [comment]
Adding `google` to GOOGLE_DOMAINS will ensure .google domains are contained, however I do not know what problems this may cause.

**Comment by Perflyst** [comment]
Should be fixed with latest release already
https://github.com/containers-everywhere/contain-google/commit/afe3ba447dd7b18bd401abe6784ce3b345c206ec
