### ISSUE TITLE
fuckoffgoogle.de incorrectly contained

### ISSUE THREAD

**Issue by hackerncoder** [containers-everywhere/contain-google#91]
I came here because google containers incorrectly contained fuckoffgoogle.de.

This incorrectly containing seems to be a problem... #49 #61 #63 #68 #74 #81 

However the pr #89 fixes all of them (I tested all the domains with the fix). 

Please accept the PR.

**Comment by hackerncoder** [comment]
My PR #92 also fixes this issue

**Comment by Perflyst** [comment]
Closed with https://github.com/containers-everywhere/contain-google/pull/89
