### ISSUE TITLE
Container disturbs Sign in with Google pop ups

### ISSUE THREAD

**Issue by ferritopia** [containers-everywhere/contain-google#93]
Hi developers, 

I want to report a bug I found really annoying for me, it happens everytime I use sign in with Google on every website. When sign in pop up appears, I chose my Google account then I get stuck in loading screen. 

Usually it will close the pop up automatically, but it just loading screen and it's unsuccessfully login to website using Google.

Thanks in advance.

**Comment by iljapanic** [comment]
I'm running into the same issue. I understand that it's a feature and works as intended. But I wonder if there is a way to circumvent the container for authentication purposes?

I want to keep Google contained, but some of the services I use don't allow other login options, therfore forcing me to disable the extension or switch browsers.

**Comment by situplastik** [comment]
We are working on it. PR #114 solve that problem, allowing to add more hosts to Google Container. It's a problem detected in several issues :)

**Comment by situplastik** [comment]
@Perflyst that issue can be cloused with #114
