### ISSUE TITLE
Not allowed to add account

### ISSUE THREAD

**Issue by luisdralves** [containers-everywhere/contain-google#98]
I already have an account inside google container, which is working fine. However, when I try to add an account, I get the following message:

> #### Couldn't sign you in
> This browser or app may not be secure. **[Learn more](https://support.google.com/accounts/answer/7675428?hl=en-GB)**
> Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

Firefox 81.0.1 (64 bit), Arch Linux

**Comment by hackerncoder** [comment]
I just tested this, and got no error.

It could be other extensions doing something that results in this error.

**Comment by luisdralves** [comment]
Yes, It must have been something else. I logged in with only google container enabled and after re-enabling my other extensions, it is fine. Sorry for bothering you.
